name: "cargo-install"
description: "GitHub action for cache-efficient Rust crates installation"
inputs:
  # Global input parameters
  crate:
    description: "Name of the crate to install"
    required: true
  features:
    description: "Features of the crate to enable."
    required: false
  locked:
    description: "Use the crate Cargo.lock if available."
    required: false
    default: "true"
  args:
    description: "Arguments added to the `cargo install` command."
    required: false
  cache-key:
    description: "Additional key added to the automatic cache key."
    required: false

  # Crates.io installation
  version:
    description: "Version of the crate to install."
    required: true
    default: "latest"

  # Git installation
  git:
    description: "Git repository to install the crate from."
    required: false
  branch:
    description: "Branch to install the crate from."
    required: false
  tag:
    description: "Tag to install the crate from."
    required: false
  commit:
    description: "Commit to install the crate from."
    required: false
  rev: # alias for commit
    description: "Commit to install the crate from."
    required: false

outputs:
  version:
    description: "The version of the crate that has been installed."
  cache-hit:
    description: "A boolean indicating whether the crate was restored from cache."
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: "yellow"
  icon: "package"
