name: "cargo-install"
description: "GitHub action for cache-efficient Rust crates installation"
inputs:
  crate:
    description: "Name of the crate to install"
    required: true
  version:
    description: "Version range to install."
    required: true
    default: "latest"
  features:
    description: "Features of the crate to enable."
    required: false
  locked:
    description: "Use the crate Cargo.lock if available."
    required: false
    default: "false"
    deprecationMessage: "Use the `args` input with `--locked` instead."
  args:
    description: "Arguments added to the `cargo install` command."
    required: false
  cache-key:
    description: "Additional key added to the automatic cache key."
    required: false
outputs:
  version:
    description: "The version of the crate that has been installed."
  cache-hit:
    description: "A boolean indicating whether the crate was restored from cache."
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: "yellow"
  icon: "package"
